In [18]:
# ter a biblioteca no anconda e importa ela
import numpy as np

In [19]:
#array a partir de uma lista

quantidade = [2,5,10,20,35]
custo = [100,150,450,320,195]


In [20]:
arr1 = np.array(quantidade)

In [21]:
arr2 = np.array(custo)

In [23]:
# essa forma so funciona com o numpy se nao daria erro 
estoque = arr1 * arr2 

In [24]:
estoque

array([ 200,  750, 4500, 6400, 6825])

In [25]:
custo = [100,200,300,400]
venda = [125,235,355,490]


In [26]:
arr3 = np.array(custo)

In [27]:
arr4 = np.array(venda)

In [28]:
lucro = arr4 - arr3

In [29]:
lucro

array([25, 35, 55, 90])

In [30]:
# Arrays a partir do numpy

In [31]:
# arange()
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
# começa no 10 vai ate 21 de 2 em 2
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [33]:
# começa no 10 vai ate 101, de 2 em 2, com numero reais(float)
np.arange(10,101,2, dtype=float)

array([ 10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98., 100.])

In [34]:
# ele tem comando com range ele recebe inicio fim e quantidade de casa que quer que ande
#linspace ()

In [37]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

bibliotecas, pacostes e funções
função = max() min() len()

pacote = math = sqrt() , pow(), log() , exp(), sen(), cos()

biblioteca = math = sqrt() , pow(), log() , exp(), sen(), cos() / modulo 2 = varias outras funções

In [38]:
#Random - rand, randn e randint

In [39]:
np.random.rand(10)

array([0.44585882, 0.16526455, 0.31235567, 0.29238671, 0.2617641 ,
       0.81969811, 0.69613335, 0.88949912, 0.41591774, 0.2460804 ])

In [40]:
np.random.randn(15)

array([-1.21780066,  2.04181879,  0.41352054, -0.65006707, -0.07707889,
       -0.42558907, -0.52939392, -1.27543956, -0.54324458,  0.02434978,
       -0.58277855, -1.00484643,  1.78561858,  1.16409212, -0.84404004])

In [41]:
# ele retorna numero aleatorios de acordo com o que foi passado de 10 a 100 por exemplo 
np.random.randint(10, 100, 30)

array([49, 13, 77, 68, 25, 91, 54, 79, 18, 76, 88, 30, 44, 43, 81, 39, 94,
       56, 52, 81, 61, 40, 83, 37, 80, 10, 13, 51, 56, 13])

In [42]:
#zeros e uns

In [43]:
# se a saida tem ([[0., 0., 0., 0.])) ele e bidimencional
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])